### PR TITLE
Test

### PR DESCRIPTION
**Pull request by roc102**

### CODE REVIEW

**Comment by roc102** [comment]
improved responsiveness

**Review by arpittyagi102 — APPROVED** [review]
Thank you so much for your contribution, I will be merging your PR

**Comment by roc102** [comment]
Hi @arpittyagi102,

You are most welcome. I have made some changes to improve mobile responsiveness, but you can also work on enhancing the UI to make it better and more interactive for both desktop and mobile devices.

Thank you for your prompt response and for considering my contribution. I've attached some screenshots for your reference.

Thanks & have a great day ahead!

Screenshot (79)
Screenshot (80)
Screenshot (78)
Screenshot (77)

**Comment by roc102** [comment]
Arpit when you are active let me know, I will make the pull request again, there was some issue and this PR has been closed.

**Comment by arpittyagi102** [comment]
just open the PR again, and i will merge it

**Comment by roc102** [comment]
Yeah, check it out now!

**Pull request closed without merging**
