### PR TITLE
Add counter in place of add to cart

### PR DESCRIPTION
**Pull request by kushalnigam0604**
Please check it once.

### CODE REVIEW

**Review by arpittyagi102 — APPROVED** [review]
hey, this is good

**Review by arpittyagi102 — APPROVED** [review]
a few changes
- [ ] make the increment and decrement boxes green colored
- [ ] make a box in between them which contains the count value

**Comment by kushalnigam0604** [comment]
Changes completed.

**Review by arpittyagi102 — APPROVED** [review]
Thank you so much for your contribution, I am merging this pull request
Please give this repository a star 🌟

**Pull request merged**
