### PR TITLE
Issue_Solved

### PR DESCRIPTION
**Pull request by RoniSikder**
This problem Occurs because in Product.js file one you mess up with the bootstrap's keyword "Active"

### CODE REVIEW

**Review by arpittyagirocks — COMMENTED** [review]
Hey, Thank you for fixing the bug.
Is it my browser or Netlify, but it seems scroll animations are not working properly
Have a look at the pull request preview

**Comment by RoniSikder** [comment]
I have just solve the issue (Bug) not focusing on the animation part

**Review by arpittyagirocks — COMMENTED** [review]
I think the animation problem is still not solved see the difference betweeen 
https://deploy-preview-31--humaridukan.netlify.app/ 
and 
https://humaridukan.netlify.app/

**Comment by arpittyagi102** [comment]
Hey @RoniSikder, Are you stilll working on it or Do you need help ?

**Pull request closed without merging**
