### PR TITLE
fix: Made the cart component responsive

### PR DESCRIPTION
**Pull request by avinashji1302**
Made changes in "Checkout.Css" in order to make responsive ....Please check and if there is any issue Please let me know

### CODE REVIEW

**Review by arpittyagi102 — APPROVED** [review]
Hey @avinashji1302, This looks amazing !
just adjust the price tag in and cart in mobile view, and i will merge the changes.

**Comment by avinashji1302** [comment]
> Hey @avinashji1302, This looks amazing ! just adjust the price tag in and cart in mobile view, and i will merge the changes.

Hii Arpit ! I am unble to find "Price tag' could You please send me the screen shot or elaborate it

**Review by arpittyagi102 — COMMENTED** [review]
## this is what i am talking about

image

**Comment by avinashji1302** [comment]
> ## this is what i am talking about
> image



I updated the Css ....   Please check....    and text are lengthy so its only possible for Medium mobile phone not for small phone

**Review by arpittyagi102 — COMMENTED** [review]
As the texts are lengthy make the content flex-direction vertical, which would make the content visible, even in smaller phones, if you can do that

**Comment by avinashji1302** [comment]
> As the texts are lengthy make the content flex-direction vertical, which would make the content visible, even in smaller phones, if you can do that

Okk...I will try do tonight .. but please check I updated the Css ..

**Comment by avinashji1302** [comment]
> > ## this is what i am talking about
> > image
> 
> I updated the Css .... Please check.... and text are lengthy so its only possible for Medium mobile phone not for small phone



> As the texts are lengthy make the content flex-direction vertical, which would make the content visible, even in smaller phones, if you can do that


Check my previous commit

**Comment by avinashji1302** [comment]
Updated One

Updated css

**Comment by avinashji1302** [comment]
@arpittyagi102   I fixed It ..Now Cart Component is fully Responsive  for all Kind of device... Please check!

**Review by arpittyagi102 — APPROVED** [review]
Thank you so much for your contribution, I am merging the changes
Please give this repository a star 🌟

**Comment by avinashji1302** [comment]
> Thank you so much for your contribution, I am merging the changes Please give this repository a star 🌟

Sure !

**Pull request merged**
