### PR TITLE
Light / Dark mode Toggle added to the theme

### PR DESCRIPTION
**Pull request by Akash1965**
This PR solves issue #22 
### Changes
Added a toggle button on th Navbar and used `useState` and `useContext` hooks for toggling light/dark modes

### CODE REVIEW

**Review by arpittyagirocks — CHANGES_REQUESTED** [review]
Hey, this looks amazing !, Just a few changes to make it perfect.
Things which also needs to be changed when switching to light theme
- search bar placeholder in navbar
- lower navbar
- breadcrumb on checkout page
- input forms on checkout page

**Comment by arpittyagirocks** [comment]
Use this color "#00adff", Also if you could add a toggle instead of a button, then it would be amazing

**Comment by Akash1965** [comment]
Hi @arpittyagirocks I have made the commit. Please check how's it. If any further modifications are required then do let me know

**Review by arpittyagirocks — COMMENTED** [review]
This is looking good, just final changes
text color in lower navbar and text color in input boxes change them to black

**Comment by arpittyagi102** [comment]
Hey @Akash1965, Are you still working on it or do you need help ?

**Pull request closed without merging**
