### PR TITLE
add cart products sorting functionality

### PR DESCRIPTION
**Pull request by sohaibaumer**

### CODE REVIEW

**Review by arpittyagi102 — COMMENTED** [review]
Please have a look at deploy preview, you have added this in cart system instead of all products

**Comment by sohaibaumer** [comment]
oh you this need functionality for all the products instead of cart products? Let me fix, please assign.

**Comment by arpittyagi102** [comment]
give a comment on the isse, so that i can assign you

**Comment by sohaibaumer** [comment]
NVM already fixed it and opened a new PR, you can check and merge.

**Pull request closed without merging**
