### PR TITLE
fixing existing product

### PR DESCRIPTION
**Pull request by roc102**
I have fixed the issue of existing product using redux state but there is a problem you need to implement a button or something which will increase or decrease the count of the quantity and according to the quantity the price will be updated. Like others E-commerce website does.

cart

### CODE REVIEW

**Review by arpittyagi102 — COMMENTED** [review]
Hey, amazing work !!
also add a reducer logic to subtract the count in item, to reduce the number of products in store

And will you please be able to add the button too,
just add the button to incease and decrease in src/product/product2.js

**Comment by roc102** [comment]
I have updated the following code by adding a reducer logic to remove and add the existing product, To resolve the issue with existing products, I included buttons to increase or decrease the product quantity and update the cost accordingly. Secondly I saw that After adding 4 to 5 products to the cart, I noticed an overflow issue. To address this, I added a scrollbar to ensure smooth display of the products. Lastly, I implemented a dialog box to prompt the user for confirmation when removing an item from the cart. 


Screenshot (180)
Screenshot (182)
Screenshot (183)

**Review by arpittyagi102 — APPROVED** [review]
This is amazing !! Thank you so much for you contribution, i am merging this PR
Please give this repository a star 🌟

**Comment by roc102** [comment]
You're welcome! I'm glad you find my contribution amazing. Definitely! I have given the repository a star 🌟. I appreciate your gratitude and I'm always here to assist you with any questions or tasks you have. Let me know if there's anything else I can help you with! 

Well I have updated the buttons so now it looks more prettier than before, Hope you will merge this PR and close it soon.

Screenshot (184)

**Pull request merged**
